/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Conversor;

/**
 *
 * @author Matias
 */
public class Conversor extends javax.swing.JFrame {

    private final String[] unidades_distancia = { "KM", "M", "CM", "MI", "IN" };
    private final String[] unidades_memoria = { "GB", "MB", "KB", "B", "b" };
    private final String[] unidades_peso = { "TON", "KG", "G", "MG" };
    private final String[] unidades_temperatura = { "C", "K", "F" };
    private final String[] unidades_tiempo = { "DIA", "HR", "MIN", "SEG" };
    
    /**
     * Creates new form Conversor
     */
    public Conversor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        text1_textfield = new javax.swing.JTextField();
        text2_textfield = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        unidad_combo = new javax.swing.JComboBox<>();
        unidades1_combo = new javax.swing.JComboBox<>();
        unidades2_combo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel1.setText("Conversor de valores");

        text1_textfield.setText("jTextField1");

        text2_textfield.setText("jTextField2");

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jButton1.setText("¡Convertir!");
        jButton1.setMaximumSize(new java.awt.Dimension(100, 29));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 29));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 29));

        unidad_combo.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        unidad_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Distancia", "Memoria", "Peso", "Temperatura", "Tiempo" }));
        unidad_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidad_comboActionPerformed(evt);
            }
        });

        unidades1_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KM", "M", "CM", "MI", "IN" }));
        unidades1_combo.setMaximumSize(new java.awt.Dimension(60, 20));
        unidades1_combo.setPreferredSize(new java.awt.Dimension(60, 20));

        unidades2_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KM", "M", "CM", "MI", "IN" }));
        unidades2_combo.setMaximumSize(new java.awt.Dimension(60, 20));
        unidades2_combo.setPreferredSize(new java.awt.Dimension(60, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(text1_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(unidades1_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unidad_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text2_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unidades2_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidad_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text2_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text1_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unidades2_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unidades1_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unidad_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidad_comboActionPerformed
        // TODO add your handling code here:
        unidades1_combo.removeAllItems();
        unidades2_combo.removeAllItems();
        
        if (unidad_combo.getSelectedItem().equals("Distancia"))
        {
            for (String unidades_distancia1 : unidades_distancia) {
                unidades1_combo.addItem(unidades_distancia1);
                unidades2_combo.addItem(unidades_distancia1);
            }
        }
        else if (unidad_combo.getSelectedItem().equals("Memoria"))
        {
            for (String unidades_memoria1 : unidades_memoria) {
                unidades1_combo.addItem(unidades_memoria1);
                unidades2_combo.addItem(unidades_memoria1);
            }
        }
        else if (unidad_combo.getSelectedItem().equals("Peso"))
        {
            for (String unidades_pesol : unidades_peso) {
                unidades1_combo.addItem(unidades_pesol);
                unidades2_combo.addItem(unidades_pesol);
            }
        }
        else if (unidad_combo.getSelectedItem().equals("Temperatura"))
        {
            for (String unidades_temperatural : unidades_temperatura) {
                unidades1_combo.addItem(unidades_temperatural);
                unidades2_combo.addItem(unidades_temperatural);
            }
        }
        else if (unidad_combo.getSelectedItem().equals("Tiempo"))
        {
            for (String unidades_tiempo1 : unidades_tiempo) {
                unidades1_combo.addItem(unidades_tiempo1);
                unidades2_combo.addItem(unidades_tiempo1);
            }
        }
    }//GEN-LAST:event_unidad_comboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField text1_textfield;
    private javax.swing.JTextField text2_textfield;
    private javax.swing.JComboBox<String> unidad_combo;
    private javax.swing.JComboBox<String> unidades1_combo;
    private javax.swing.JComboBox<String> unidades2_combo;
    // End of variables declaration//GEN-END:variables
}
